sudo: required
dist: trusty
language: cpp

notifications: never

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libstdc++6-dev
      env: COMPILER=g++-6

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DTest=ON ..
  - make
