sudo: required
dist: trusty

os: linux
language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake

before_script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version
  - mkdir build
  - cd build
  - cmake ..

script: make
